export interface GroupField {
  key: string;
  type: "text" | "textarea" | "image" | "list";
  label?: string;
}

export interface SectionGroup {
  id: string;
  title: string;
  icon: string;
  desc?: string;
  fields: GroupField[];
}

const homeGroups: SectionGroup[] = [
  {
    id: "hero",
    title: "Hero",
    icon: "panorama",
    desc: "Immagine di sfondo, titolo, descrizione e CTA",
    fields: [
      { key: "hero_img_src", type: "image", label: "Immagine sfondo" },
      { key: "hero_badge", type: "text", label: "Badge" },
      { key: "hero_title_line1", type: "text", label: "Titolo riga 1" },
      { key: "hero_title_line2", type: "text", label: "Titolo riga 2 (colorato)" },
      { key: "hero_description", type: "textarea", label: "Descrizione" },
      { key: "hero_cta_label", type: "text", label: "Testo bottone" },
      { key: "hero_badge_247", type: "text", label: "Badge 24/7" },
      { key: "hero_badge_eu", type: "text", label: "Badge EU" },
      { key: "hero_support_label", type: "text", label: "Testo supporto H24" },
    ],
  },
  {
    id: "valori",
    title: "I Nostri Punti di Forza",
    icon: "handshake",
    desc: "Badge, titolo e 3 card valori",
    fields: [
      { key: "valori_badge", type: "text", label: "Badge sezione" },
      { key: "valori_title", type: "text", label: "Titolo sezione" },
      { key: "valore1_title", type: "text", label: "Titolo valore 1" },
      { key: "valore1_desc", type: "textarea", label: "Descrizione valore 1" },
      { key: "valore2_title", type: "text", label: "Titolo valore 2" },
      { key: "valore2_desc", type: "textarea", label: "Descrizione valore 2" },
      { key: "valore3_title", type: "text", label: "Titolo valore 3" },
      { key: "valore3_desc", type: "textarea", label: "Descrizione valore 3" },
    ],
  },
  {
    id: "servizi",
    title: "I Nostri Servizi",
    icon: "assignment",
    desc: "Badge, titolo, sottotitolo e griglia servizi",
    fields: [
      { key: "servizi_badge", type: "text", label: "Badge sezione" },
      { key: "servizi_title", type: "text", label: "Titolo sezione" },
      { key: "servizi_subtitle", type: "textarea", label: "Sottotitolo" },
      { key: "servizio_nazionale_img_src", type: "image", label: "Immagine nazionale" },
      { key: "servizio_nazionale_badge", type: "text", label: "Badge nazionale" },
      { key: "servizio_nazionale_title", type: "text", label: "Titolo nazionale" },
      { key: "servizio_nazionale_desc", type: "textarea", label: "Descrizione nazionale" },
      { key: "servizio_industriali_title", type: "text", label: "Titolo industriali" },
      { key: "servizio_industriali_desc", type: "textarea", label: "Descrizione industriali" },
      { key: "servizio_industriali_feat1", type: "text", label: "Feature 1 industriali" },
      { key: "servizio_industriali_feat2", type: "text", label: "Feature 2 industriali" },
      { key: "servizio_express_title", type: "text", label: "Titolo express" },
      { key: "servizio_express_desc", type: "textarea", label: "Descrizione express" },
      { key: "servizio_express_badge", type: "text", label: "Badge express" },
      { key: "servizio_express_feat", type: "text", label: "Feature express" },
      { key: "servizio_internazionale_title", type: "text", label: "Titolo internazionale" },
      { key: "servizio_internazionale_desc", type: "textarea", label: "Descrizione internazionale" },
      { key: "servizio_internazionale_area", type: "text", label: "Area internazionale" },
    ],
  },
  {
    id: "flotta",
    title: "La Nostra Flotta",
    icon: "local_shipping",
    desc: "Titolo, descrizione, features e immagine",
    fields: [
      { key: "flotta_title", type: "text", label: "Titolo sezione" },
      { key: "flotta_desc", type: "textarea", label: "Descrizione" },
      { key: "flotta_feat1_label", type: "text", label: "Feature 1" },
      { key: "flotta_feat2_label", type: "text", label: "Feature 2" },
      { key: "flotta_feat3_label", type: "text", label: "Feature 3" },
      { key: "flotta_img_src", type: "image", label: "Immagine flotta" },
    ],
  },
  {
    id: "whychoose",
    title: "Perché Sceglierci",
    icon: "stars",
    desc: "Immagine, sticker, badge e 3 card",
    fields: [
      { key: "whychoose_img_src", type: "image", label: "Immagine" },
      { key: "whychoose_sticker_title", type: "text", label: "Titolo sticker" },
      { key: "whychoose_sticker_subtitle", type: "text", label: "Sottotitolo sticker" },
      { key: "whychoose_badge", type: "text", label: "Badge sezione" },
      { key: "whychoose_title", type: "text", label: "Titolo sezione" },
      { key: "whychoose1_title", type: "text", label: "Titolo card 1" },
      { key: "whychoose1_desc", type: "textarea", label: "Descrizione card 1" },
      { key: "whychoose2_title", type: "text", label: "Titolo card 2" },
      { key: "whychoose2_desc", type: "textarea", label: "Descrizione card 2" },
      { key: "whychoose3_title", type: "text", label: "Titolo card 3" },
      { key: "whychoose3_desc", type: "textarea", label: "Descrizione card 3" },
    ],
  },
  {
    id: "cta",
    title: "Richiedi un Preventivo",
    icon: "quickreply",
    desc: "Badge, titolo, sottotitolo e campi form",
    fields: [
      { key: "quote_badge", type: "text", label: "Badge sezione" },
      { key: "quote_title", type: "text", label: "Titolo" },
      { key: "quote_subtitle", type: "textarea", label: "Sottotitolo" },
      { key: "quote_field_company", type: "text", label: "Label Ragione Sociale" },
      { key: "quote_field_company_placeholder", type: "text", label: "Placeholder Ragione Sociale" },
      { key: "quote_field_email", type: "text", label: "Label Email" },
      { key: "quote_field_email_placeholder", type: "text", label: "Placeholder Email" },
      { key: "quote_field_pickup", type: "text", label: "Label Carico" },
      { key: "quote_field_pickup_placeholder", type: "text", label: "Placeholder Carico" },
      { key: "quote_field_destination", type: "text", label: "Label Destinazione" },
      { key: "quote_field_destination_placeholder", type: "text", label: "Placeholder Destinazione" },
      { key: "quote_field_notes", type: "text", label: "Label Note" },
      { key: "quote_field_notes_placeholder", type: "text", label: "Placeholder Note" },
      { key: "quote_submit_label", type: "text", label: "Testo bottone" },
    ],
  },
];

const serviziGroups: SectionGroup[] = [
  {
    id: "hero",
    title: "Hero",
    icon: "panorama",
    desc: "Immagine, titolo e sottotitolo",
    fields: [
      { key: "hero_img_src", type: "image", label: "Immagine sfondo" },
      { key: "hero_badge", type: "text", label: "Badge" },
      { key: "hero_title", type: "text", label: "Titolo" },
      { key: "hero_subtitle", type: "textarea", label: "Sottotitolo" },
    ],
  },
  {
    id: "distribuzione",
    title: "Consegne in Toda Italia",
    icon: "local_shipping",
    desc: "Badge, titolo, descrizione, immagine e CTA",
    fields: [
      { key: "distribuzione_badge", type: "text", label: "Badge" },
      { key: "distribuzione_title", type: "text", label: "Titolo" },
      { key: "distribuzione_desc", type: "textarea", label: "Descrizione" },
      { key: "distribuzione_img_src", type: "image", label: "Immagine" },
      { key: "distribuzione_cta_label", type: "text", label: "Testo CTA" },
    ],
  },
  {
    id: "nazionale",
    title: "Trasporto Nazionale",
    icon: "route",
    desc: "Area, titolo, descrizione, features e CTA",
    fields: [
      { key: "nazionale_area", type: "text", label: "Area" },
      { key: "nazionale_title", type: "text", label: "Titolo" },
      { key: "nazionale_desc", type: "textarea", label: "Descrizione" },
      { key: "nazionale_feat1", type: "text", label: "Feature 1" },
      { key: "nazionale_feat2", type: "text", label: "Feature 2" },
      { key: "nazionale_cta_label", type: "text", label: "Testo CTA" },
    ],
  },
  {
    id: "express",
    title: "Spedizioni Express",
    icon: "bolt",
    desc: "Icona, titolo, descrizione e badge",
    fields: [
      { key: "express_title", type: "text", label: "Titolo" },
      { key: "express_desc", type: "textarea", label: "Descrizione" },
      { key: "express_badge", type: "text", label: "Badge" },
    ],
  },
  {
    id: "sicurezza",
    title: "Sicurezza",
    icon: "security",
    desc: "Titolo, features e testi grandi",
    fields: [
      { key: "sicurezza_title", type: "text", label: "Titolo sezione" },
      { key: "sicurezza_feat1_title", type: "text", label: "Feature 1 titolo" },
      { key: "sicurezza_feat1_desc", type: "text", label: "Feature 1 descrizione" },
      { key: "sicurezza_feat2_title", type: "text", label: "Feature 2 titolo" },
      { key: "sicurezza_feat2_desc", type: "text", label: "Feature 2 descrizione" },
      { key: "sicurezza_big_text", type: "text", label: "Testo grande" },
      { key: "sicurezza_big_subtext", type: "text", label: "Sottotesto" },
    ],
  },
  {
    id: "internazionale",
    title: "Trasporto Internazionale",
    icon: "public",
    desc: "Badge, titolo, descrizione, features e immagine",
    fields: [
      { key: "internazionale_badge", type: "text", label: "Badge" },
      { key: "internazionale_title", type: "text", label: "Titolo" },
      { key: "internazionale_desc", type: "textarea", label: "Descrizione" },
      { key: "internazionale_feat1", type: "text", label: "Feature 1" },
      { key: "internazionale_feat2", type: "text", label: "Feature 2" },
      { key: "internazionale_img_src", type: "image", label: "Immagine" },
    ],
  },
  {
    id: "mezzi",
    title: "Veicoli Moderni e Affidabili",
    icon: "garage",
    desc: "Badge, titolo e 3 card mezzi",
    fields: [
      { key: "mezzi_badge", type: "text", label: "Badge" },
      { key: "mezzi_title", type: "text", label: "Titolo" },
      { key: "mezzi_feat1_title", type: "text", label: "Card 1 titolo" },
      { key: "mezzi_feat1_desc", type: "textarea", label: "Card 1 descrizione" },
      { key: "mezzi_feat2_title", type: "text", label: "Card 2 titolo" },
      { key: "mezzi_feat2_desc", type: "textarea", label: "Card 2 descrizione" },
      { key: "mezzi_feat3_title", type: "text", label: "Card 3 titolo" },
      { key: "mezzi_feat3_desc", type: "textarea", label: "Card 3 descrizione" },
    ],
  },
  {
    id: "consulenza",
    title: "Richiedi una Consulenza",
    icon: "support_agent",
    desc: "Badge, titolo, descrizione, 4 item e CTA",
    fields: [
      { key: "consulenza_badge", type: "text", label: "Badge" },
      { key: "consulenza_title", type: "text", label: "Titolo" },
      { key: "consulenza_desc", type: "textarea", label: "Descrizione" },
      { key: "consulenza_feat1_title", type: "text", label: "Item 1 titolo" },
      { key: "consulenza_feat1_desc", type: "text", label: "Item 1 descrizione" },
      { key: "consulenza_feat2_title", type: "text", label: "Item 2 titolo" },
      { key: "consulenza_feat2_desc", type: "text", label: "Item 2 descrizione" },
      { key: "consulenza_feat3_title", type: "text", label: "Item 3 titolo" },
      { key: "consulenza_feat3_desc", type: "text", label: "Item 3 descrizione" },
      { key: "consulenza_feat4_title", type: "text", label: "Item 4 titolo" },
      { key: "consulenza_feat4_desc", type: "text", label: "Item 4 descrizione" },
      { key: "consulenza_img_src", type: "image", label: "Immagine" },
      { key: "consulenza_cta_label", type: "text", label: "Testo CTA" },
    ],
  },
  {
    id: "features",
    title: "Feature Bar",
    icon: "fact_check",
    desc: "4 feature con label e sub",
    fields: [
      { key: "feature1_label", type: "text", label: "Feature 1" },
      { key: "feature1_sub", type: "text", label: "Feature 1 sub" },
      { key: "feature2_label", type: "text", label: "Feature 2" },
      { key: "feature2_sub", type: "text", label: "Feature 2 sub" },
      { key: "feature3_label", type: "text", label: "Feature 3" },
      { key: "feature3_sub", type: "text", label: "Feature 3 sub" },
      { key: "feature4_label", type: "text", label: "Feature 4" },
      { key: "feature4_sub", type: "text", label: "Feature 4 sub" },
    ],
  },
];

const chiSiamoGroups: SectionGroup[] = [
  {
    id: "hero",
    title: "Hero",
    icon: "panorama",
    desc: "Immagine, titolo e sottotitolo",
    fields: [
      { key: "hero_img_src", type: "image", label: "Immagine sfondo" },
      { key: "hero_badge", type: "text", label: "Badge" },
      { key: "hero_title", type: "text", label: "Titolo" },
      { key: "hero_subtitle", type: "textarea", label: "Sottotitolo" },
    ],
  },
  {
    id: "storia",
    title: "La Nostra Storia",
    icon: "history",
    desc: "3 paragrafi di testo e immagine",
    fields: [
      { key: "story_p1", type: "textarea", label: "Paragrafo 1" },
      { key: "story_p2", type: "textarea", label: "Paragrafo 2" },
      { key: "story_p3", type: "textarea", label: "Paragrafo 3" },
      { key: "story_img_src", type: "image", label: "Immagine" },
      { key: "story_caption_title", type: "text", label: "Didascalia titolo" },
      { key: "story_caption_sub", type: "text", label: "Didascalia descrizione" },
    ],
  },
  {
    id: "metriche",
    title: "Metriche",
    icon: "bar_chart",
    desc: "3 box con label e sub",
    fields: [
      { key: "metric1_label", type: "text", label: "Metrica 1" },
      { key: "metric1_sub", type: "text", label: "Metrica 1 sub" },
      { key: "metric2_label", type: "text", label: "Metrica 2" },
      { key: "metric2_sub", type: "text", label: "Metrica 2 sub" },
      { key: "metric3_label", type: "text", label: "Metrica 3" },
      { key: "metric3_sub", type: "text", label: "Metrica 3 sub" },
    ],
  },
  {
    id: "valori",
    title: "I Nostri Valori",
    icon: "handshake",
    desc: "Titolo e 4 card valori",
    fields: [
      { key: "valori_title", type: "text", label: "Titolo sezione" },
      { key: "valore1_title", type: "text", label: "Titolo valore 1" },
      { key: "valore1_desc", type: "textarea", label: "Descrizione valore 1" },
      { key: "valore2_title", type: "text", label: "Titolo valore 2" },
      { key: "valore2_desc", type: "textarea", label: "Descrizione valore 2" },
      { key: "valore3_title", type: "text", label: "Titolo valore 3" },
      { key: "valore3_desc", type: "textarea", label: "Descrizione valore 3" },
      { key: "valore4_title", type: "text", label: "Titolo valore 4" },
      { key: "valore4_desc", type: "textarea", label: "Descrizione valore 4" },
    ],
  },
];

const contattiGroups: SectionGroup[] = [
  {
    id: "hero",
    title: "Hero",
    icon: "panorama",
    desc: "Immagine, titolo e sottotitolo",
    fields: [
      { key: "hero_img_src", type: "image", label: "Immagine sfondo" },
      { key: "hero_badge", type: "text", label: "Badge" },
      { key: "hero_title", type: "text", label: "Titolo" },
      { key: "hero_subtitle", type: "textarea", label: "Sottotitolo" },
    ],
  },
  {
    id: "form",
    title: "Richiedi un Preventivo",
    icon: "quickreply",
    desc: "Titolo, sottotitolo, campi form e privacy",
    fields: [
      { key: "form_title", type: "text", label: "Titolo" },
      { key: "form_subtitle", type: "textarea", label: "Sottotitolo" },
      { key: "form_field_company", type: "text", label: "Label Nome/R.Sociale" },
      { key: "form_field_company_placeholder", type: "text", label: "Placeholder Nome" },
      { key: "form_field_phone", type: "text", label: "Label Telefono" },
      { key: "form_field_phone_placeholder", type: "text", label: "Placeholder Telefono" },
      { key: "form_field_email", type: "text", label: "Label Email" },
      { key: "form_field_email_placeholder", type: "text", label: "Placeholder Email" },
      { key: "form_field_service", type: "text", label: "Label Servizio" },
      { key: "form_option1", type: "text", label: "Opzione 1" },
      { key: "form_option2", type: "text", label: "Opzione 2" },
      { key: "form_option3", type: "text", label: "Opzione 3" },
      { key: "form_option4", type: "text", label: "Opzione 4" },
      { key: "form_field_details", type: "text", label: "Label Dettagli" },
      { key: "form_field_details_placeholder", type: "text", label: "Placeholder Dettagli" },
      { key: "form_privacy_label", type: "text", label: "Testo privacy" },
      { key: "form_submit_label", type: "text", label: "Testo bottone" },
    ],
  },
  {
    id: "info",
    title: "Centro Operativo",
    icon: "location_on",
    desc: "Titolo, descrizione e mappa",
    fields: [
      { key: "info_office_title", type: "text", label: "Titolo" },
      { key: "info_office_desc", type: "text", label: "Descrizione" },
      { key: "info_office_map", type: "text", label: "Mappa" },
    ],
  },
  {
    id: "legale",
    title: "Dati Societari",
    icon: "description",
    desc: "Ragione sociale, P.IVA, REA, PEC",
    fields: [
      { key: "info_legal_title", type: "text", label: "Titolo" },
      { key: "info_legal_company_label", type: "text", label: "Label Ragione Sociale" },
      { key: "info_legal_company", type: "text", label: "Ragione Sociale" },
      { key: "info_legal_vat_label", type: "text", label: "Label P.IVA" },
      { key: "info_legal_vat", type: "text", label: "P.IVA" },
      { key: "info_legal_rea_label", type: "text", label: "Label REA" },
      { key: "info_legal_rea", type: "text", label: "REA" },
      { key: "info_legal_pec_label", type: "text", label: "Label PEC" },
      { key: "info_legal_pec", type: "text", label: "PEC" },
    ],
  },
];

const globaleGroups: SectionGroup[] = [
  {
    id: "logo",
    title: "Logo e Brand",
    icon: "logo_dev",
    desc: "Logo del sito e nome brand",
    fields: [
      { key: "logo_img_src", type: "image", label: "Logo (immagine)" },
      { key: "logo_text", type: "text", label: "Testo logo" },
    ],
  },
  {
    id: "nav",
    title: "Menu di Navigazione",
    icon: "menu_book",
    desc: "Testo delle voci del menu principale",
    fields: [
      { key: "nav_home", type: "text", label: "Voce Home" },
      { key: "nav_services", type: "text", label: "Voce Servizi" },
      { key: "nav_about", type: "text", label: "Voce Chi Siamo" },
      { key: "nav_contact", type: "text", label: "Voce Contatti" },
    ],
  },
  {
    id: "phone",
    title: "Telefono",
    icon: "call",
    desc: "Numero e testo pulsante chiamata",
    fields: [
      { key: "phone_number", type: "text", label: "Numero di telefono" },
      { key: "phone_label", type: "text", label: "Testo pulsante chiamata" },
    ],
  },
  {
    id: "footer",
    title: "Footer",
    icon: "web_stories",
    desc: "Contenuti del footer del sito",
    fields: [
      { key: "footer_sede_title", type: "text", label: "Titolo sede" },
      { key: "footer_sede_indirizzo", type: "text", label: "Indirizzo" },
      { key: "footer_sede_citta", type: "text", label: "Città e CAP" },
      { key: "footer_sede_paese", type: "text", label: "Paese" },
      { key: "footer_contatti_title", type: "text", label: "Titolo contatti" },
      { key: "footer_telefono", type: "text", label: "Telefono" },
      { key: "footer_email", type: "text", label: "Email" },
      { key: "footer_pec", type: "text", label: "PEC" },
      { key: "footer_legali_title", type: "text", label: "Titolo legali" },
      { key: "footer_piva", type: "text", label: "Partita IVA" },
      { key: "footer_rea", type: "text", label: "Numero REA" },
      { key: "footer_privacy_label", type: "text", label: "Testo link Privacy" },
      { key: "privacy_policy_url", type: "text", label: "URL Privacy Policy" },
      { key: "footer_termini_label", type: "text", label: "Testo link Cookie" },
      { key: "cookie_policy_url", type: "text", label: "URL Cookie Policy" },
      { key: "footer_seguici_title", type: "text", label: "Titolo social" },
      { key: "footer_copyright", type: "textarea", label: "Testo copyright" },
      { key: "footer_lang_label", type: "text", label: "Label lingua" },
      { key: "footer_version", type: "text", label: "Versione" },
    ],
  },
];

export const sectionGroupsMap: Record<string, SectionGroup[]> = {
  home: homeGroups,
  servizi: serviziGroups,
  "chi-siamo": chiSiamoGroups,
  contatti: contattiGroups,
  globale: globaleGroups,
};

export function getGroupsForSection(section: string): SectionGroup[] {
  return sectionGroupsMap[section] || [];
}
